title: 3초연구소
description: 3초연구소 공식 블로그입니다.
author: 3초연구소자
avatar: /logo.png
email: @gmail.com
url: https://gilblog.netlify.app

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 3seclab
  card: summary
logo: logo.png
social:
  name: 3초연구소
  links:
    - https://twitter.com/3seclab
    - https://instagram.com/3seclab.ofiicial
    - https://github.com/ngzhio
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
